/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__SEvec_fig_util
#define __PYX_HAVE__SEvec_fig_util


#ifndef __PYX_HAVE_API__SEvec_fig_util

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(double) *global_c;

#endif /* !__PYX_HAVE_API__SEvec_fig_util */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initSEvec_fig_util(void);
#else
PyMODINIT_FUNC PyInit_SEvec_fig_util(void);
#endif

#endif /* !__PYX_HAVE__SEvec_fig_util */
